# ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
# GitHub Actions workflow: Release Drafter
#
# Automatically updates the draft release notes based on pull requests merged into the main or master branch.
# Uses the release-drafter app.
#
# See: https://github.com/release-drafter/release-drafter
# ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

name: Release Drafter

# Trigger the workflow on:
# - Pushes to main or master (commonly used release branches)
# - Pull request events that may affect the release (open/reopen/update)
on:
  push:
    branches: [main, master]
  pull_request:
    types: [opened, reopened, synchronize]

# Default permissions for the workflow
permissions:
  contents: read

jobs:
  update_release_draft:
    # Override permissions to allow writing to releases and pull requests
    permissions:
      contents: write           # Allows creating/updating the draft release
      pull-requests: write      # Allows adding PR metadata to the draft
    runs-on: ubuntu-latest

    steps:
      # Run the official Release Drafter GitHub Action
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Authenticates the action
